apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-test
  name: k8s-test
spec:
  ports:
    - name: "5050"
      port: 5050
      protocol: TCP
      targetPort: 5000
  selector:
    app: k8s-test
  type: ClusterIP
status:
  loadBalancer: {}
